#ifndef CLI_CONSTANTS_H_
#define CLI_CONSTANTS_H_

#define SCALE 2

#define FIELD_ROW 1
#define FIELD_COL 2
#define FIELD_WIDTH 10
#define FIELD_HEIGHT 20

#define GAP 5

#define SCORE_ROW FIELD_ROW
#define SCORE_COL (FIELD_COL + FIELD_WIDTH * 2 + GAP)
#define SCORE_HEIGHT 3
#define SCORE_WIDTH 10

#define HIGH_SCORE_ROW (SCORE_ROW + SCORE_HEIGHT)
#define HIGH_SCORE_COL SCORE_COL
#define HIGH_SCORE_HEIGHT 3
#define HIGH_SCORE_WIDTH SCORE_WIDTH

#define NEXT_ROW (HIGH_SCORE_ROW + HIGH_SCORE_HEIGHT)
#define NEXT_COL SCORE_COL
#define NEXT_HEIGHT 7
#define NEXT_WIDTH SCORE_WIDTH

#define LEVEL_ROW (NEXT_ROW + NEXT_HEIGHT + 1)
#define LEVEL_COL SCORE_COL
#define LEVEL_HEIGHT 3
#define LEVEL_WIDTH SCORE_WIDTH

#define PAUSE_ROW LEVEL_ROW + LEVEL_HEIGHT
#define PAUSE_COL SCORE_COL
#define PAUSE_HEIGHT 1
#define PAUSE_WIDTH SCORE_WIDTH

#define HINT_ROW FIELD_ROW
#define HINT_COL (SCORE_COL + SCORE_WIDTH + GAP)
#define HINT_HEIGHT 8
#define HINT_WIDTH 30

#define GAME_OVER_ROW (HINT_ROW + HINT_HEIGHT + GAP)
#define GAME_OVER_COL HINT_COL
#define GAME_OVER_HEIGHT 8
#define GAME_OVER_WIDTH 30

#define ESC 27

#endif